# Generated by Django 3.2.4 on 2023-10-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id_respuesta', models.IntegerField(db_column='idrespuesta', primary_key=True, serialize=False)),
                ('name1', models.CharField(db_column='Nombres', max_length=100)),
                ('apellidop', models.CharField(db_column='Apellidop', max_length=100)),
                ('apellidom', models.CharField(db_column='Apellidom', max_length=100)),
                ('matricula', models.CharField(db_column='Matricula', max_length=100)),
                ('consideras', models.CharField(db_column='Considerascom', max_length=100)),
                ('compra', models.CharField(db_column='Compraint', max_length=100)),
                ('notificacion', models.CharField(db_column='Notwhats', max_length=100)),
                ('experiencia', models.CharField(db_column='Maneraco', max_length=100)),
                ('productos', models.CharField(db_column='Producnu', max_length=100)),
                ('pago', models.CharField(db_column='pagotarj', max_length=100)),
            ],
            options={
                'db_table': 'Formulario',
            },
        ),
    ]
