# Generated by Django 3.2.4 on 2023-10-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='marcat',
            field=models.IntegerField(db_column='marcat', default=2, max_length=100),
            preserve_default=False,
        ),
    ]
