# Generated by Django 3.2.4 on 2023-10-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_formulario_marcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='id_respuesta',
        ),
        migrations.AddField(
            model_name='formulario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
